services:
  - type: web
    name: chess-game-fullstack
    runtime: docker
    plan: starter
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # You'll set this manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET  
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "24h"
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"
      - key: CORS_ORIGIN
        value: "*"
      - key: LOG_LEVEL
        value: "info"
    buildFilter:
      paths:
      - "**"
      ignoredPaths:
      - "node_modules/**"
      - "client/node_modules/**"
      - "logs/**"
      - ".git/**"
      - "*.md"
    healthCheckPath: /api/health
    autoDeploy: true